import {test} from 'node:test';
import assert from 'node:assert/strict';
import {dedupePhoneNumbers,numberKey,normalizeIdentity,renderPhrase,buildIdentityPrompt,languageOptions,languagePolicy,supportedLanguages} from '../public/identity.js';
test('formatted and provider phone numbers resolve to the same identity key',()=>{assert.equal(numberKey('+40 21 000 0104'),numberKey('+40210000104'))});
test('duplicate Twilio number records appear once in selectors',()=>{const numbers=[{phone_number:'+14155550104',friendly_name:'Main'},{phone_number:'+1 (415) 555-0104',friendly_name:'Duplicate'},{phone_number:'+14155550105',friendly_name:'Second'}];assert.deepEqual(dedupePhoneNumbers(numbers),[numbers[0],numbers[2]])});
test('older agents acquire conversation defaults without losing custom names',()=>{const a=normalizeIdentity({name:'Elena',company:'Atelier SRL',instructions:'Custom business guidance'});assert.equal(a.name,'Elena');assert.equal(a.instructions,'Custom business guidance');assert.equal(a.addressMode,'formal');assert.ok(a.opening);assert.ok(a.closing)});
test('language selector offers native names and enforces a single spoken language',()=>{assert.ok(supportedLanguages.length>=8);const options=languageOptions('Italian','live-language');assert.match(options,/🇮🇹 Italiano · Italy/);assert.match(options,/id="live-language-policy"/);assert.match(options,/Speak only in Italian throughout the call/);assert.equal(normalizeIdentity({language:'Italian'}).language,'Italian');assert.match(languagePolicy('Italian'),/Do not switch languages/);assert.equal(normalizeIdentity({language:'Unsupported'}).language,'Romanian')});
test('phrase placeholders are resolved without evaluating inserted text',()=>{const a=normalizeIdentity({name:'Elena',company:'Atelier SRL'});assert.equal(renderPhrase('Salut {first_name}, sunt {agent_name} de la {company_name}.',a,'Andrei Popescu'),'Salut Andrei, sunt Elena de la Atelier SRL.');assert.equal(renderPhrase('{full_name}',a,'{agent_name}'),'{agent_name}')});
test('bridge prompt carries identity details and applies the selected language to every spoken phrase',()=>{const a=normalizeIdentity({name:'Mihai',company:'Firma B',language:'Italian',introduction:'Sunt {agent_name}, asistent AI.',opening:'Salut {first_name}!',addressMode:'first-name',addressInstructions:'Nu folosi titluri.',closing:'La revedere de la {company_name}!'});const prompt=buildIdentityPrompt(a,'Ioana Ionescu','Confirm delivery');for(const text of ['Mihai','Firma B','Salut Ioana!','given name','Nu folosi titluri.','La revedere de la Firma B!','Confirm delivery','Always identify yourself as an AI assistant','Speak only in Italian throughout the call','Do not switch languages'])assert.ok(prompt.includes(text),text);assert.ok(!prompt.includes('{first_name}'))});
