import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://localhost:3000/dashboard');
 await page.getByRole('button',{name:'Translate to Romanian'}).click();
 await page.getByRole('heading',{name:'Mai aproape de clienții tăi.'}).waitFor();
 assert.equal(await page.locator('html').getAttribute('lang'),'ro');
 await page.getByRole('link',{name:'Numere de telefon',exact:true}).click();
 assert.equal(await page.locator('#country').inputValue(),'RO');
 assert.equal(await page.locator('.number-card').count(),6);
 await page.getByLabel('Prefix sau cifre').fill('0264');
 await page.getByRole('button',{name:'Caută numere'}).click();
 assert.equal(await page.locator('.number-card').count(),2);
 await page.getByRole('button',{name:'Alege ↗',exact:true}).first().click();
 await page.getByText('Următorul număr al companiei.').waitFor();
 await page.getByRole('button',{name:'Adaugă numărul demo'}).click();
 await page.getByRole('link',{name:'Agent AI',exact:true}).click();
 assert.equal(await page.locator('#language').inputValue(),'Romanian');
 await page.getByLabel('Numele agentului',{exact:true}).fill('Elena');
 await page.getByRole('button',{name:'Switch to English'}).click();
 assert.equal(await page.getByLabel('Numele agentului',{exact:true}).inputValue(),'Elena');
 assert.equal(await page.locator('#language').inputValue(),'Romanian');
 await page.getByRole('button',{name:'Translate to Romanian'}).click();
 await page.getByRole('button',{name:'Salvează agentul'}).click();
 await page.reload();
 await page.getByRole('heading',{name:'Configurează agentul tău.'}).waitFor();
 assert.equal(await page.getByLabel('Numele agentului',{exact:true}).inputValue(),'Elena');
 assert.equal(await page.locator('#language').inputValue(),'Romanian');
 await page.getByRole('link',{name:'Prezentare generală',exact:true}).click();
 await page.getByRole('button',{name:'Încearcă demo-ul ↗'}).click();
 assert.match(await page.locator('#from').inputValue(),/^\+40/);
 assert.equal(await page.locator('#contact').inputValue(),'Andrei Popescu');
 assert.equal(await page.locator('#destination').inputValue(),'+40700000101');
 await page.locator('#destination').fill('+14155550142');
 assert.equal(await page.locator('#destination').evaluate(e=>e.checkValidity()),false);
 await page.locator('#destination').fill('+40700000101');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Pornește apelul simulat'}).click();
 await page.getByText('Conectat · Simulare',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Încheie apelul simulat'}).click();
 await page.getByText('Fără înregistrare · Acest apel a fost simulat').waitFor();
 await page.getByRole('button',{name:'Gata',exact:true}).click();
 await page.getByLabel('Filtrează după stare').selectOption('Completed');
 assert.equal(await page.locator('#history-status').inputValue(),'Completed');
 await page.getByRole('link',{name:'Setări',exact:true}).click();
 await page.getByRole('heading',{name:'Ce îți trebuie pentru un apel real în România'}).waitFor();
 await page.getByRole('button',{name:'Deschide consola pentru apeluri reale ↗'}).click();
 await page.getByLabel('Token de acces la spațiul de lucru').fill('invalid-workspace-token-12345');
 await page.getByRole('button',{name:'Conectează spațiul',exact:true}).click();
 await page.getByText('Este necesară autentificarea în spațiul de lucru.').waitFor();
 await page.getByRole('button',{name:'Închide fereastra'}).click();
 await page.getByRole('link',{name:'Prezentare generală',exact:true}).click();
 await page.screenshot({path:'/tmp/masscall-ro-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/masscall-ro-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Switch to English'}).click();
 await page.getByRole('heading',{name:'Closer to your customers.'}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: Romanian marketplace, area-code filter, translations, persistent locale, preserved form data, Romanian agent, one-click demo, +40 validation, call states, recording states, status filters and mobile layout.');
}finally{await browser.close()}
