import {test} from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/telephony.js';
const originalFetch=globalThis.fetch;
const token='test-workspace-token-123456789';
function request(action,{auth=true,method='POST',body={}}={}){const req={url:'/api/telephony?action='+action,method,headers:{authorization:auth?'Bearer '+token:''},body};let status;let payload;const res={writeHead(s){status=s},end(v){payload=v}};return handler(req,res).then(()=>({status,data:JSON.parse(payload)}))}
function env(){process.env.MASSCALL_ADMIN_TOKEN=token;process.env.TWILIO_ACCOUNT_SID='AC'+'1'.repeat(32);process.env.TWILIO_AUTH_TOKEN='test';process.env.ENABLE_LIVE_CALLS='true';process.env.ENABLE_NUMBER_PURCHASES='false';process.env.VOICE_BRIDGE_URL='wss://bridge.example.com/media';process.env.VOICE_BRIDGE_SECRET='test-bridge-secret'}
test('paid and recording APIs reject unauthenticated requests',async()=>{env();for(const action of ['call','purchase','rename-number','recordings&call=CA'+'1'.repeat(32),'audio&recording=RE'+'1'.repeat(32)]){const r=await request(action,{auth:false});assert.equal(r.status,401)}});
test('purchases stay disabled until explicitly enabled',async()=>{env();const r=await request('purchase',{body:{number:'+14155550142',confirmPurchase:true}});assert.equal(r.status,403)});
test('number labels require an owned Twilio number and update its FriendlyName',async()=>{env();const sid='PN'+'a'.repeat(32),requests=[];globalThis.fetch=async(url,options)=>{requests.push({url:String(url),method:options.method,body:options.body&&new URLSearchParams(options.body)});return Response.json({sid,friendly_name:'Reception'})};try{const r=await request('rename-number',{body:{sid,friendlyName:'Sales line'}});assert.equal(r.status,200);assert.equal(requests.length,2);assert.equal(requests[0].method,'GET');assert.equal(requests[1].method,'POST');assert.match(requests[1].url,new RegExp(sid));assert.equal(requests[1].body.get('FriendlyName'),'Sales line');assert.equal((await request('rename-number',{body:{sid:'invalid',friendlyName:'Name'}})).status,400);assert.equal((await request('rename-number',{body:{sid,friendlyName:'x'.repeat(65)}})).status,400)}finally{globalThis.fetch=originalFetch}});
test('calls require recording consent and a valid international destination',async()=>{env();let r=await request('call',{body:{to:'+14155550142',from:'+14155550104',consent:true}});assert.equal(r.status,400);r=await request('call',{body:{to:'+1234',from:'+14155550104',consent:true,recordingConsent:true}});assert.equal(r.status,400)});
test('recorded call validates caller ownership and sends dual-channel recording with signed context',async()=>{env();let created;globalThis.fetch=async(url,options)=>{if(String(url).includes('IncomingPhoneNumbers'))return Response.json({incoming_phone_numbers:[{phone_number:'+14155550104'}]});created=new URLSearchParams(options.body);return Response.json({sid:'CA'+'2'.repeat(32),status:'queued'})};try{const r=await request('call',{body:{to:'+447700900123',from:'+14155550104',consent:true,recordingConsent:true,objective:'Confirm appointment',contact:'Ioana Ionescu',agent:{name:'Andreea',language:'Romanian',introduction:'Sunt {agent_name}, asistent AI.',opening:'Bună ziua, {full_name}!',closing:'La revedere!',addressMode:'full-name'}}});assert.equal(r.status,201);assert.equal(created.get('To'),'+447700900123');assert.equal(created.get('Record'),'true');assert.equal(created.get('RecordingChannels'),'dual');assert.equal(created.get('TimeLimit'),'300');assert.match(created.get('Twiml'),/este înregistrat/);assert.match(created.get('Twiml'),/language="ro-RO" voice="Polly.Carmen"/);assert.match(created.get('Twiml'),/signature/);assert.doesNotMatch(created.get('Twiml'),/test-bridge-secret/);const chunks=[...created.get('Twiml').matchAll(/name="context\d+" value="([^"]+)"/g)].map(m=>m[1]).join('');const context=JSON.parse(Buffer.from(chunks,'base64url').toString());assert.equal(context.contact,'Ioana Ionescu');assert.equal(context.agent.opening,'Bună ziua, {full_name}!');assert.equal(context.agent.closing,'La revedere!');assert.equal(context.agent.addressMode,'full-name')}finally{globalThis.fetch=originalFetch}});
test('malformed recording IDs cannot become provider URLs',async()=>{env();const r=await request('audio&recording=..%2Fsecret',{method:'GET'});assert.equal(r.status,400)});
test('upstream errors propagate without fake success',async()=>{env();globalThis.fetch=async()=>Response.json({message:'Invalid credentials'},{status:401});try{const r=await request('numbers',{method:'GET'});assert.equal(r.status,401);assert.equal(r.data.error,'Invalid credentials')}finally{globalThis.fetch=originalFetch}});
test('number search defaults to Romanian voice inventory',async()=>{env();let requested;globalThis.fetch=async url=>{requested=String(url);return Response.json({available_phone_numbers:[]})};try{const r=await request('search',{method:'GET'});assert.equal(r.status,200);assert.match(requested,/AvailablePhoneNumbers\/RO\/Local\.json\?VoiceEnabled=true/)}finally{globalThis.fetch=originalFetch}});
