import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000/dashboard');
await page.getByRole('heading',{name:'Closer to your customers.'}).waitFor();
await page.screenshot({path:'/tmp/masscall-desktop.png',fullPage:true});
await page.getByRole('link',{name:'Phone numbers',exact:true}).click();
await page.getByRole('button',{name:'Choose ↗'}).first().click();
await page.getByRole('button',{name:'Add preview number'}).click();
await page.getByRole('link',{name:'AI agent',exact:true}).click();
await page.getByLabel('Numele agentului',{exact:true}).fill('Taylor');
await page.getByRole('button',{name:'Salvează agentul',exact:true}).click();
await page.reload();assert.equal(await page.getByLabel('Numele agentului',{exact:true}).inputValue(),'Taylor');
await page.getByRole('link',{name:'Make a call',exact:true}).click();
await page.getByLabel('Call from',{exact:true}).selectOption({index:1});
await page.getByLabel('Contact name',{exact:true}).fill('Test Contact');
await page.getByLabel('Mobile number',{exact:true}).fill('+40700000101');
await page.getByLabel('What should the call accomplish?').fill('Confirm tomorrow’s appointment');
await page.getByRole('checkbox').check();
await page.getByRole('button',{name:'Start simulated call'}).click();
await page.getByText('Connected · Simulation',{exact:true}).waitFor();
await page.getByRole('button',{name:'End simulated call'}).click();
await page.getByText('No recording · This call was simulated').waitFor();
await page.getByRole('button',{name:'Done',exact:true}).click();
await page.getByRole('textbox',{name:'Search calls'}).fill('Test Contact');
assert.equal(await page.locator('tbody tr').count(),1);
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV'}).click();assert.equal((await download).suggestedFilename(),'masscall-conversations.csv');
await page.getByRole('link',{name:'Settings',exact:true}).click();
await page.getByRole('button',{name:'Open live workspace console ↗'}).click();
await page.getByLabel('Workspace access token').fill('invalid-workspace-token-12345');
await page.getByRole('button',{name:'Connect workspace',exact:true}).click();
await page.getByText('Workspace authentication required.').waitFor();
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('link',{name:'Overview',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/masscall-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'No mobile horizontal overflow');
assert.deepEqual(errors,[]);
console.log('PASS: number onboarding, agent persistence, call simulation, recording empty state, history filtering, CSV export, live authorization, and mobile layout');
await browser.close();
