import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||undefined});
const page=await browser.newPage({viewport:{width:1280,height:1000}});
page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const sid='CA'+'c'.repeat(32),requests=[];let status='ringing',releaseCall;
const numbers=[{sid:'PN'+'a'.repeat(32),phone_number:'+40210000104',friendly_name:'Vico'},{sid:'PN'+'b'.repeat(32),phone_number:'+40210000105',friendly_name:'Vico secundar'}];
try{
 await page.addInitScript(()=>{localStorage.setItem('masscall-v1',JSON.stringify({people:[{id:'ana',name:'Ana',phone:'+40735555123',category:'Existing customers'}],callTemplates:[{id:'saved-test',name:'Șablon salvat',objective:'Confirmă următorul pas.',opening:'Salută persoana.',talkingPoints:'Întreabă când poate discuta.',closing:'Mulțumește.',completionTrigger:'S-a stabilit următorul pas.',branches:[{when:'Persoana este ocupată',then:'Propune să revenim.'}]}]}))});
 await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url()),action=url.searchParams.get('action');let data={};
  if(action==='numbers'&&route.request().headers().authorization==='Bearer invalid-workspace-token-12345'){await route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:'Workspace authentication required.'})});return}
  if(action==='numbers')data={incoming_phone_numbers:numbers};
  else if(action==='calls')data={calls:requests.length?[{sid,status,to:requests[0].to,from:numbers[0].phone_number,duration:'10'}]:[]};
  else if(action==='engine-config')data={livekitEnabled:false};
  else if(url.pathname==='/api/campaigns')data={campaigns:[]};
  else if(action==='call'){requests.push(route.request().postDataJSON());await new Promise(resolve=>{releaseCall=resolve});data={sid,status:'queued'}}
  else if(action==='call-status')data={sid,status,to:'+40735555123'};
  else if(action==='hangup'){status='completed';data={sid,status}}
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});
 });
 await mkdir('output/playwright',{recursive:true});
 await page.goto('http://localhost:3000/dashboard');
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-mode=personal]').waitFor();
 await page.screenshot({path:'output/playwright/onboarding-welcome-mobile.png',fullPage:true});
 assert.ok((await page.locator('[data-mode=business]').boundingBox()).y<700,'Both audience options are discoverable on mobile');
 assert.ok(await page.locator('#modal-content').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'Welcome fits mobile');
 await page.setViewportSize({width:1280,height:1000});
 await page.locator('[data-mode=personal]').click();
 await page.locator('#onboarding-back').click();
 await page.locator('[data-mode=business]').click();
 await page.locator('#onboarding-back').click();
 await page.locator('[data-mode=personal]').click();
 await page.locator('#owner-token').fill('invalid-workspace-token-12345');
 await page.locator('#owner-login button[type=submit]').click();
 await page.getByText('Codul de acces este invalid.',{exact:true}).waitFor();
 await page.locator('#owner-token').fill('test-workspace-token-123456789');
 await page.locator('#owner-login button[type=submit]').click();
 await page.locator('.onboarding-guide').waitFor();
 await mkdir('output/playwright',{recursive:true});
 await page.screenshot({path:'output/playwright/experience-choice.png',fullPage:true});
 await page.getByRole('heading',{name:'Ce rezolvăm astăzi?'}).waitFor();
 assert.equal(await page.locator('.live-workspace-menu [data-panel=campaigns]').isVisible(),false);
 await page.locator('[data-guide-dismiss]').click();
 await page.locator('[data-guide-show]').click();
 await page.locator('[data-task=availability]').click();
 assert.equal(await page.locator('#call-template').inputValue(),'starter:availability');
 await page.locator('#real-objective').fill('Întreabă dacă au produsul în stoc.');
 await page.locator('.experience-switch').click();
 await page.locator('[data-mode=business]').click();
 await page.screenshot({path:'output/playwright/experience-business.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'output/playwright/experience-business-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Business home fits mobile');
 await page.setViewportSize({width:1280,height:1000});
 assert.equal(await page.locator('.live-workspace-menu [data-panel=campaigns]').isVisible(),true);
 await page.locator('.live-workspace-menu [data-panel=call]').click();
 assert.equal(await page.locator('#real-objective').inputValue(),'Întreabă dacă au produsul în stoc.');
 await page.locator('#call-template').selectOption('starter:test-conversation');
 await page.locator('#call-template').waitFor();
 const brandBox=await page.locator('.sidebar .brand').boundingBox(),menuBox=await page.locator('.live-workspace-menu').boundingBox();
 assert.ok(menuBox.x<brandBox.x+240&&menuBox.y>brandBox.y,'Call menu sits below the Masscall brand in the left sidebar');
 assert.ok(await page.locator('.brand-emblem img').evaluate(image=>image.complete&&image.naturalWidth>0),'Sidebar mascot loads');
 assert.match(await page.locator('.live-workspace-menu button').first().innerText(),/Acasă/);
 assert.equal(await page.locator('html').getAttribute('lang'),'ro');
 assert.equal(await page.locator('#real-call').getAttribute('data-mode'),'simple');
 assert.equal(await page.locator('#real-engine').isVisible(),false);
 assert.equal(await page.locator('#real-template').isVisible(),false);
 assert.equal(await page.locator('#real-starter').isVisible(),false);
 assert.equal(await page.locator('#call-template').inputValue(),'starter:test-conversation');
 await page.locator('#call-template').selectOption('saved:saved-test');
 assert.equal(await page.locator('#real-objective').inputValue(),'Confirmă următorul pas.');
 await page.locator('#call-template').selectOption('starter:appointment-confirmation');
 assert.match(await page.locator('#real-objective').inputValue(),/programarea/);
 const goal='Confirmă programarea de mâine la ora 10:00, la recepție.';
 await page.locator('#real-objective').fill(goal);
 await page.locator('#real-person').selectOption('ana');
 assert.equal(await page.locator('#real-objective').inputValue(),goal);
 assert.equal(await page.locator('#call-template').inputValue(),'starter:appointment-confirmation');
 await page.locator('#real-from').selectOption(numbers[1].phone_number);
 assert.equal(await page.locator('#real-objective').inputValue(),goal);
 assert.equal(await page.locator('#live-studio-slot').isVisible(),false);
 await page.locator('.live-workspace-menu [data-panel=max]').click();
 assert.equal(await page.locator('#call-setup-title').innerText(),'MAX SETTINGS');
 assert.equal(await page.locator('#real-engine').isVisible(),true);
 await page.locator('#call-voice').selectOption('gleam');
 await page.locator('.live-workspace-menu [data-panel=call]').click();
 assert.equal(await page.locator('#real-objective').inputValue(),goal);
 await page.locator('#real-contact').fill('Ana');
 await page.locator('#real-to').fill('+40 (735) 555-123');
 await page.locator('#real-call [name=consent]').check();
 await page.locator('#real-call [name=recordingConsent]').check();
 await page.locator('#real-objective').fill('');
 await page.locator('#real-call button[type=submit]').click();
 assert.equal(requests.length,0);
 await page.locator('#real-objective').fill(goal);
 await page.locator('#real-call button[type=submit]').click();
 await page.locator('#review-dial').waitFor();
 assert.equal(requests.length,0);
 assert.equal(await page.locator('.call-review-brief').first().innerText(),goal);
 await page.locator('#review-edit').click();
 assert.equal(requests.length,0);
 await page.locator('#real-call button[type=submit]').click();
 await page.locator('#review-dial').click();
 await page.waitForFunction(()=>document.querySelector('#real-call button[type=submit]').disabled);
 await page.locator('#real-call').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 await page.waitForTimeout(100);
 assert.equal(requests.length,1);
 releaseCall();
 await page.getByText('Telefonul sună',{exact:true}).waitFor();
 assert.equal(requests[0].objective,goal);assert.equal(requests[0].to,'+40735555123');assert.equal(requests[0].agent.language,'Romanian');assert.equal(requests[0].agent.voice,'gleam');assert.equal(requests[0].callPlan.templateName,'Confirmare de programare');
 assert.equal(await page.locator('#real-call button[type=submit]').isDisabled(),true);
 status='in-progress';
 await page.getByText('Apel conectat',{exact:true}).waitFor();
 await page.locator('#end-test-call').click();
 await page.getByText('Apel încheiat',{exact:true}).waitFor();
 assert.equal(await page.locator('#real-call button[type=submit]').isDisabled(),false);
 await mkdir('output/playwright',{recursive:true});
 await page.screenshot({path:'output/playwright/call-flow-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'output/playwright/call-flow-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal overflow on mobile');
 await page.locator('#mobile-menu-toggle').click();
 assert.equal(await page.locator('#mobile-menu-toggle').getAttribute('aria-expanded'),'true');
 const mobileMenuBox=await page.locator('.live-workspace-menu').boundingBox();
 assert.ok(mobileMenuBox&&mobileMenuBox.x>=0&&mobileMenuBox.x+mobileMenuBox.width<=390,'Mobile menu is fully visible');
 await page.screenshot({path:'output/playwright/call-menu-mobile.png'});
 await page.locator('.live-workspace-menu [data-panel=max]').click();
 assert.equal(await page.locator('#mobile-menu-toggle').getAttribute('aria-expanded'),'false');
 assert.equal(await page.locator('#call-setup-title').innerText(),'MAX SETTINGS');
 assert.deepEqual(errors,[]);
 console.log('PASS: Romanian UI, CALL and MAX SETTINGS, template selection, call overrides, status polling, hangup, mobile layout.');
 await page.setViewportSize({width:1280,height:1000});
 await page.goto('http://localhost:3000/studio');assert.equal(new URL(page.url()).pathname,'/dashboard');await page.locator('#owner-token').waitFor();
 assert.equal(await page.evaluate(()=>localStorage.getItem('masscall-experience')),'business');
 assert.equal(await page.locator('#owner-token').inputValue(),'');
 await page.locator('#owner-token').fill('test-workspace-token-123456789');
 await page.locator('#owner-login button[type=submit]').click();
 await page.locator('.onboarding-guide').waitFor();
 await page.locator('.experience-switch').click();
 await page.locator('[data-mode=personal]').click();
 assert.match(await page.locator('.onboarding-guide').innerText(),/1 DIN 3/);
 await page.locator('[data-guide-target=call]').click();
 assert.equal(await page.locator('#call-template').inputValue(),'starter:availability');
 assert.equal(requests.length,1,'Onboarding navigation never creates a call');
 await page.goto('http://localhost:3000/demo.html');assert.equal(new URL(page.url()).pathname,'/');await page.locator('#demo-form').waitFor();
 assert.equal(await page.getByRole('heading',{name:'Apeluri AI, în română.'}).count(),1);
 assert.ok(await page.locator('.hero-art img').evaluate(image=>image.complete&&image.naturalWidth>0),'Brand mascot loads');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Landing page fits mobile viewport');
}finally{await browser.close()}
